const String TITLE = 'TITLE TITLE TITLE';
const String SUBTITLE = 'SUBTITLE SUBTITLE SUBTITLE';
const String TEXT =
    'TEXT TEXT TEXT TEXT TEXT TEXT TEXT TEXT TEXTTEXT TEXT TEXT TEXT TEXT TEXT TEXT TEXT TEXT TEXT TEXT TEXT TEXT TEXT TEXT TEXT TEXT TEXT';
